name: Django Github Action

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Version ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running the tests 
        run: 
          python manage.py test
  deploy:
    runs-on: ubuntu-latest
    name: Deploy our Django app to Render
    needs: build  # Ensures build completes before deploying
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          branch: main